
#ifndef GAP__ANIMATION_LIB__HPP_
#define GAP__ANIMATION_LIB__HPP_

#ifdef GAP_ANIMATIONSYSTEM_STATIC_DEFINE
#  define GAP_ANIMATION_DLL_EXPORT
#  define GAP_ANIMATIONSYSTEM_NO_EXPORT
#else
#  ifndef GAP_ANIMATION_DLL_EXPORT
#    ifdef AnimationSystem_EXPORTS
        /* We are building this library */
#      define GAP_ANIMATION_DLL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define GAP_ANIMATION_DLL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef GAP_ANIMATIONSYSTEM_NO_EXPORT
#    define GAP_ANIMATIONSYSTEM_NO_EXPORT 
#  endif
#endif

#ifndef GAP_ANIMATIONSYSTEM_DEPRECATED
#  define GAP_ANIMATIONSYSTEM_DEPRECATED __declspec(deprecated)
#endif

#ifndef GAP_ANIMATIONSYSTEM_DEPRECATED_EXPORT
#  define GAP_ANIMATIONSYSTEM_DEPRECATED_EXPORT GAP_ANIMATION_DLL_EXPORT GAP_ANIMATIONSYSTEM_DEPRECATED
#endif

#ifndef GAP_ANIMATIONSYSTEM_DEPRECATED_NO_EXPORT
#  define GAP_ANIMATIONSYSTEM_DEPRECATED_NO_EXPORT GAP_ANIMATIONSYSTEM_NO_EXPORT GAP_ANIMATIONSYSTEM_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef GAP_ANIMATIONSYSTEM_NO_DEPRECATED
#    define GAP_ANIMATIONSYSTEM_NO_DEPRECATED
#  endif
#endif

#endif /* GAP__ANIMATION_LIB__HPP_ */
